// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_articles from "./routes/api/articles.ts";
import * as $api_index_refresh from "./routes/api/index/refresh.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $scores from "./routes/scores.tsx";
import * as $sources from "./routes/sources.tsx";
import * as $AppPopoverForm from "./islands/AppPopoverForm.tsx";
import * as $AppRefreshIndex from "./islands/AppRefreshIndex.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/articles.ts": $api_articles,
    "./routes/api/index/refresh.ts": $api_index_refresh,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/scores.tsx": $scores,
    "./routes/sources.tsx": $sources,
  },
  islands: {
    "./islands/AppPopoverForm.tsx": $AppPopoverForm,
    "./islands/AppRefreshIndex.tsx": $AppRefreshIndex,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
